spring:
  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalheekuuuheekuuheekuuheekuu"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studydb?useSSL=false&allowPublicKeyRetrieval=true  # Public Key Retrieval 문제 해결
    username: root
    password: ymca1124!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    show-sql: true
    open-in-view: false
  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG